services:
  ditto-talkinghead:
    build: .
    container_name: ditto-container
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
    volumes:
      - ./src:/app/src
      - ./data:/app/data
      - ./checkpoints:/app/checkpoints
      - ./output:/app/output
    working_dir: /app
    stdin_open: true
    tty: true
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu] 